name: personal_gym_log_app_th5_g5
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.1
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  flutter_local_notifications: ^21.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  pdf: ^3.11.3
  share_plus: ^10.1.2
  timezone: ^0.11.0
  flutter_timezone: ^4.1.1
  intl: ^0.20.2
  font_awesome_flutter: ^11.0.0
  url_launcher: 6.2.1
  youtube_player_flutter: 9.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gym_banner.png